name: autoclaimexpense
app:
  runtime: python@3.12
  env:
    GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  build:
    system:
      - apt-get update
      - apt-get install -y \
          tesseract-ocr \
          libtesseract-dev \
          poppler-utils \
          libgl1-mesa-glx \
          libglib2.0-0
    install:
      - pip install --no-cache-dir -r requirements.txt
    commands:
      - chmod +x ./tesseract/tesseract
  start: uvicorn main:app --host 0.0.0.0 --port 8000
  healthcheck:
    path: /serverCheck
    interval: 10
    timeout: 5
    retries: 5
