name: autoclaimexpense
app: python@3.12

options:
  ports: "8000"
  start: uvicorn main:app --host 0.0.0.0 --port 8000
  healthz: /serverCheck
  env:
    - name: GOOGLE_API_KEY
      value: ${GOOGLE_API_KEY}   # 환경변수 치환 가능 (Cloudtype dashboard에 설정)
  buildenv: []

context:
  git:
    url: https://github.com/kgj960425/ocr-expense-claim-form.git
    branch: master
