name: Scheduled Deploy (09:00 KST)

on:
  schedule:
    - cron: "0 23 * * *"   # UTC 23:00 = KST 08:00
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: kgj960425/cloudtype
          stage: main
          yaml: |
            name: ocr-expense-claim-formp-docker
            app: dockerfile
            options:
              ports: "8000"
              start: uvicorn main:app --host 0.0.0.0 --port 8000
              healthz: /serverCheck
              env:
                - name: GOOGLE_API_KEY
                  value: ${{ secrets.GOOGLE_API_KEY }}
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
